### ISSUE TITLE
Suggestions to cater for different sizes device

### ISSUE THREAD

**Issue by PhilipChng** [mahdizakizadeh/shifting_tabbar#1]
1. For Widget _buildTab, you can use `mainAxisAlignment: MainAxisAlignment.center,` in Row to cater for different length of words.
2. For `labelFlex`, `MediaQuery.of(context).devicePixelRatio` gives a better feeling across different sizes screen.

**Comment by mzakizadeh** [comment]
First of all, thanks for sharing your suggestions. I appreciate you for reading the code and trying to make it better.

And here is my thoughts on your suggestions: 
1. The reason why I didn't use `MainAxisAlignment.center` in first place is because I want icons stays fix when opening animation is firing. If you look at `Test 2` tab in these examples you'll see the effect. And that's why I calculate margins manually for each tab.

MainAxisAlignment.start:
![with](https://user-images.githubusercontent.com/10382216/57638479-18673400-75c3-11e9-8c67-c120db07850a.gif)

MainAxisAlignment.center:
![without](https://user-images.githubusercontent.com/10382216/57638480-18673400-75c3-11e9-9fa5-53499b8c4077.gif)

2. I didn't quite get what you mean. Can you explain more about how I can use `devicePixelRatio`  for `labelFlex`?

**Comment by PhilipChng** [comment]
Alright, I get it for the first point. 
For the 2nd point, the default `labelFlex` is now `1.0`. Perhaps you can make it by default using `MediaQuery.of(context).devicePixelRatio`. It looks better across different screen size in my opinion.

**Comment by PhilipChng** [comment]
Nevermind, I found 1.0 works fine. Thanks!

**Comment by mzakizadeh** [comment]
The thing is, in my opinion, there is no fixed value for `labelFlex`. There are some tricks that you can do to get a better look. First thing is to try to choose words for tab titles that have same length and then you can tune `labelFlex` value to works fine with them.
