### ISSUE TITLE
IMPORTANT - Error with null-safety

### ISSUE THREAD

**Issue by aymaalo** [mahdizakizadeh/shifting_tabbar#7]
Hi! I've updated my project to sdk: ">=2.12.0 <3.0.0" and I have an error that I can't resolve: 
```type 'List<_ShiftingTabWidget?>' is not a subtype of type 'List<Widget>' in type  cast ```

the tabs I'm using are the following: 
```
List<ShiftingTab> tabs = [
      ShiftingTab(icon: Icon(Icons.info), text: "1"),
      ShiftingTab(icon: Icon(Icons.shopping_cart_rounded), text: "2"),
      ShiftingTab(icon: Icon(Icons.group_rounded), text: "3"),
      ShiftingTab(icon: Icon(Icons.chat_bubble_rounded), text: "4"),
    ];
```

The error seems coming from p_ackage:shifting_tabbar/shifting_tabbar.dart:117:40_

Thanks for helping :D

**Comment by emem365** [comment]
@MisterB2B That seems right. The error is originating from:
https://github.com/mahdizakizadeh/shifting_tabbar/blob/15ea24350e9871f3290ceb2edf8e58bfdd15a217/lib/shifting_tabbar.dart#L118

The return type for the function is List<_ShiftingTabWidget?> while the type Cast expects the type List<_ShiftingTabWidget>.
The fix is simple enough:
https://github.com/mahdizakizadeh/shifting_tabbar/blob/15ea24350e9871f3290ceb2edf8e58bfdd15a217/lib/shifting_tabbar.dart#L131-L150
Every _ShiftingTabWidget? should be replaced with _ShiftingTabWidget, which seems correct from the point of null safety as well, since no _ShiftingTabWidget can be null.
I tried cloning the repository but there seems to be an error with some path, which makes it so that I can't clone the repository, nor does a git ref work in pubspec.yaml, since even that cannot clone the repository.
This is the error I face while cloning the repo
```
Resolving deltas: 100% (115/115), done.
error: invalid path 'example/build\ios/Runner.build/Release-iphoneos/Runner.build/dgph'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'                                                                                                                           
```
So I cannot really drop a PR or a fix for this issue as of now

**Comment by mzakizadeh** [comment]
Hello everyone,
I apologize for the late reply to the issue. Because I am a full-time student, I do not have much free time, and it's been a long time that I have not worked with Flutter. I would be happy if someone solves the problem and send a pull request. It may take a few weeks if I want to solve the problem myself.
@emem365, if you can solve the problem somehow, please send a pull request, and I'll merge your code to the repository. And If I can help somehow, please let me know.

best regards
--Mahdi

**Comment by emem365** [comment]
@mahdizakizadeh as I mentioned, I tried to but I can't clone the project. There seems to be error with a files path

**Comment by mzakizadeh** [comment]
@emem365 Is that a Git problem? I don't have any issue with cloning the project.

**Comment by aymaalo** [comment]
So nobody can fix it ? Even if we already know how to do it ?

**Comment by aymaalo** [comment]
@mahdizakizadeh @emem365

**Comment by pMertDogan** [comment]
I have the same problem with this package and git. Error is simple to fix. There is a casting problem like @emem365  mentioned.

'Class? ' cant be cast as 'Class' that's null safety
